### ISSUE TITLE
Unit LLThreads - compiler error with installed version 25 and 26

### ISSUE THREAD

**Issue by ThomasI-42** [combit/DelphiDataProviders#3]
Getting compiler error having both ListLabel25 and ListLabel26 in library path.
Maybe setting ListLabel path only in the project would be a workaround.

Error:
[dcc32 Fataler Fehler] Project.dpr(355): F2051 Unit ListLabel25 wurde mit einer unterschiedlichen Version von LLThreads.TPrintPreviewThread compiliert

How about renaming LLThreads to LLThreads26, this way LLThreads26 would be version specific?

**Comment by jbartlau** [comment]
Can you elaborate a bit on your setup? I can compile the samples and components both for V25 and V26 just fine on my machine as all the result files (BPL/DCU etc.) are in separate directories. Or does the library path for your _project_ specify both paths (i.e. the LL25 and LL26 one)?

We generally try to avoid version specific file names where it's not absolutely neccessary as this makes merging and tracking changes across versions a tad easier.

**Comment by ThomasI-42** [comment]
currently I have the following configuration:
Tools->Options->Language->Delphi Options->Library
 - $(onsDelphi)\$(onsDelphiVersion)\osLibrary\Win32\$(Config)\LL21
 - $(onsDelphi)\$(onsDelphiVersion)\osLibrary\Win32\$(Config)\LL25
 - $(onsDelphi)\$(onsDelphiVersion)\osLibrary\Win32\$(Config)\LL26

 I suspect your configuration of the LL-dcu's is here: Project->Options->Delphi Compiler->Search Path 
Such a configuration would also be possible for me.

Currently I have a project with LL26 and a project with LL21 (bde) and LL25.
I am working on replacing LL21 with the LL25 version

**Comment by jbartlau** [comment]
Right, I have a project specific path set. If that would work for you it seems to be the easiest solution.
